export type DevelopmentPhase =
  | 'INTAKE'
  | 'PREPARING'
  | 'PLANNING'
  | 'AWAITING_PLAN_APPROVAL'
  | 'IMPLEMENTING'
  | 'VERIFYING'
  | 'AWAITING_PUBLICATION_APPROVAL'
  | 'PUBLISHING'
  | 'REVIEWING'
  | 'AWAITING_MERGE'
  | 'WAITING_FOR_INPUT'
  | 'COMPLETED'
  | 'FAILED'
  | 'CANCELLED';

export const developmentPhaseTransitions: Readonly<
  Record<DevelopmentPhase, readonly DevelopmentPhase[]>
> = {
  INTAKE: ['PREPARING', 'FAILED', 'CANCELLED'],
  PREPARING: ['PLANNING', 'WAITING_FOR_INPUT', 'FAILED', 'CANCELLED'],
  PLANNING: ['AWAITING_PLAN_APPROVAL', 'WAITING_FOR_INPUT', 'FAILED', 'CANCELLED'],
  AWAITING_PLAN_APPROVAL: ['IMPLEMENTING', 'PLANNING', 'FAILED', 'CANCELLED'],
  IMPLEMENTING: ['VERIFYING', 'WAITING_FOR_INPUT', 'FAILED', 'CANCELLED'],
  VERIFYING: [
    'AWAITING_PUBLICATION_APPROVAL',
    'IMPLEMENTING',
    'WAITING_FOR_INPUT',
    'FAILED',
    'CANCELLED',
  ],
  AWAITING_PUBLICATION_APPROVAL: ['PUBLISHING', 'IMPLEMENTING', 'FAILED', 'CANCELLED'],
  PUBLISHING: ['REVIEWING', 'AWAITING_PUBLICATION_APPROVAL', 'FAILED', 'CANCELLED'],
  REVIEWING: ['AWAITING_MERGE', 'IMPLEMENTING', 'WAITING_FOR_INPUT', 'FAILED', 'CANCELLED'],
  AWAITING_MERGE: ['COMPLETED', 'IMPLEMENTING', 'FAILED', 'CANCELLED'],
  WAITING_FOR_INPUT: ['FAILED', 'CANCELLED'],
  COMPLETED: [],
  FAILED: [],
  CANCELLED: [],
};
